services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - DATABASE_URL=${DATABASE_URL}
      - SUPABASE_PROJECT_URL=${SUPABASE_PROJECT_URL}
      - SUPABASE_PUBLISHABLE_KEY=${SUPABASE_PUBLISHABLE_KEY}
      - SUPABASE_ANON_KEY=${SUPABASE_ANON_KEY}
    restart: always
